## 1. 텐서 다루기 — 개념 정리

### 1) 텐서 생성

In [ ]:
import torch

torch.zeros(2,3) # 0으로 2,3 행렬 채우기
torch.ones(2,3) # 1으로 2,3 행렬 채우기
torch.full((2,3),7.0) # 7.0으로 2,3 행렬 채우기
torch.empty(2, 3) # 초기화 안 함(쓰레기값)
torch.randn(2,3) # 랜덤 값으로 2,3 행렬 채우기
torch.randint(0,10 , (2,3)) # 랜덤 int로 2,3 행렬 채우기
torch.arange(0,10,2) # [0,2,4,6,8] — 끝값 미포함
torch.linspace(0, 1, 5) # [0, 0.25, 0.5, 0.75, 1] — 끝값 포함
torch.eye(3) # 대각 행렬

# _like 계열은 shape,dtype,device를 그대로 따라가므로 실무에서 훨씬 자주 씀

x = torch.zeros(2,3)
torch.zeros_like(x)   # x와 같은 shape/dtype/device
torch.randn_like(x)

tensor([[-1.3122,  2.3880, -0.5870],
        [-0.8766,  1.3768, -0.8739]])

### 임정혁의 궁금증


In [ ]:
# 무슨 차이일까..

a = torch.zeros(2,3)
b = torch.empty(2,3)

print(a)
print(b)    

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


torch.empty()는 0으로 초기화하는 게 아니라 초기화를 아예 안 함

지금은 새로 받은 메모리 공간에 우연히 0이 들어 있어서 그렇게 출력된 거.

실행 환경이나 시점에 따라 쓰레기값이 나올 수도 있음.